## Single layer neural network

In [ ]:
#1- First, import PyTorch
import torch

In [ ]:
#2- create an activation function for our neuron
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [ ]:
###3- Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

## Networks Using Matrix Multiplication

In [ ]:
### Solution

# Now, make our labels from our data and true weights

y = activation(torch.sum(features * weights) + bias)
print(y)

y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


In [ ]:
# to display the shape/size of any tensor
features.shape

torch.Size([1, 5])

In [ ]:
# to display the first indext in the shape array which represents the row number
features.shape[0]

1

In [ ]:
# to display the second indext in the shape array which represents the culomn number
features.shape[1]

5

In [ ]:
weights.shape

torch.Size([1, 5])

## The most efficient way for matrix multiplication

In [ ]:
##4- Solution

y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


In [ ]:
features.shape

torch.Size([1, 5])

In [ ]:
weights.shape

torch.Size([1, 5])

## Multilayer Networks 


In [ ]:
###1- Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [ ]:
features.shape

torch.Size([1, 3])

In [ ]:
W1.shape

torch.Size([3, 2])

In [ ]:
W2.shape

torch.Size([2, 1])

In [ ]:
B1.shape

torch.Size([1, 2])

In [ ]:
B2.shape

torch.Size([1, 1])

In [ ]:
### Solution

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


In [ ]:
h.shape

torch.Size([1, 2])

In [ ]:
W2.shape

torch.Size([2, 1])

In [ ]:
output.shape

torch.Size([1, 1])

## From Numpy (array) to Torch (tensor) and back

In [6]:
import torch
import numpy as np

# craete a dummy numpy array
a = np.random.rand(4,3)
a

array([[0.57653434, 0.24199678, 0.46791135],
       [0.21958086, 0.9255004 , 0.78289748],
       [0.8316196 , 0.86487606, 0.81164087],
       [0.34479192, 0.38999766, 0.0808021 ]])

In [ ]:
# numpy array
a.shape

(4, 3)

In [7]:
# convert the numpy array 'a' into pytorch tensor 'b'
b = torch.from_numpy(a)
b

tensor([[0.5765, 0.2420, 0.4679],
        [0.2196, 0.9255, 0.7829],
        [0.8316, 0.8649, 0.8116],
        [0.3448, 0.3900, 0.0808]], dtype=torch.float64)

In [ ]:
# pytorch tensor, and has the same shape as the numpy array 
b.shape

torch.Size([4, 3])

In [9]:
# go back and convert the pytorch tensor 'b' into numpy array structure 
z= b.numpy()
z

array([[0.57653434, 0.24199678, 0.46791135],
       [0.21958086, 0.9255004 , 0.78289748],
       [0.8316196 , 0.86487606, 0.81164087],
       [0.34479192, 0.38999766, 0.0808021 ]])

In [10]:
z.shape

(4, 3)

In [13]:
b.shape

torch.Size([4, 3])

In [14]:
a.shape

(4, 3)

## Operations on Tensors or Array
The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [11]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.1531, 0.4840, 0.9358],
        [0.4392, 1.8510, 1.5658],
        [1.6632, 1.7298, 1.6233],
        [0.6896, 0.7800, 0.1616]], dtype=torch.float64)

In [12]:
# Numpy array matches new values from Tensor, Performing any operation on the Pytorch Tensor will affect and change the Numpy array values and vice versa. 
a

array([[1.15306869, 0.48399357, 0.9358227 ],
       [0.43916172, 1.85100079, 1.56579497],
       [1.66323921, 1.72975212, 1.62328174],
       [0.68958384, 0.77999532, 0.1616042 ]])