## Single layer neural networks

In [ ]:
# First, import PyTorch
import torch

In [ ]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

## Networks Using Matrix Multiplication

In [ ]:
### Solution

# Now, make our labels from our data and true weights

y = activation(torch.sum(features * weights) + bias)
print(y)

y = activation((features * weights).sum() + bias)
print(y)

tensor([[0.1595]])
tensor([[0.1595]])


## The most efficient way for matrix multiplication

In [ ]:
## Solution

y = activation(torch.mm(features, weights.view(5,1)) + bias)
print(y)

tensor([[0.1595]])


## Multilayer Networks 


In [ ]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [ ]:
### Solution

h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.3171]])


## From Numpy (array) to Torch (tensor) and back

In [ ]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.48378167, 0.50168828, 0.40439898],
       [0.72630425, 0.10487308, 0.94518169],
       [0.30625661, 0.67509996, 0.23630406],
       [0.27383689, 0.40792258, 0.18536191]])

In [ ]:
b = torch.from_numpy(a)
b

tensor([[0.4838, 0.5017, 0.4044],
        [0.7263, 0.1049, 0.9452],
        [0.3063, 0.6751, 0.2363],
        [0.2738, 0.4079, 0.1854]], dtype=torch.float64)

In [ ]:
b.numpy()

array([[0.48378167, 0.50168828, 0.40439898],
       [0.72630425, 0.10487308, 0.94518169],
       [0.30625661, 0.67509996, 0.23630406],
       [0.27383689, 0.40792258, 0.18536191]])

## Operations on Tensors or Array
The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [ ]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.9676, 1.0034, 0.8088],
        [1.4526, 0.2097, 1.8904],
        [0.6125, 1.3502, 0.4726],
        [0.5477, 0.8158, 0.3707]], dtype=torch.float64)

In [ ]:
a

array([[0.96756334, 1.00337655, 0.80879795],
       [1.4526085 , 0.20974616, 1.89036339],
       [0.61251321, 1.35019992, 0.47260811],
       [0.54767379, 0.81584517, 0.37072382]])